# This is a basic workflow to help you get started with Actions

name: Mod Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Get mod name and version
      - name: Get info from info.json
        id: extract_info
        run: |
          echo "mod_name=$(jq '.name' ${{ github.workspace }}/info.json)\n" >> $GITHUB_OUTPUT
          echo "Mod name is $(jq '.name' ${{ github.workspace }}/info.json)"
          echo "mod_version=$(jq '.version' ${{ github.workspace }}/info.json)\n" >> $GITHUB_OUTPUT
          echo "Mod version is $(jq '.version' ${{ github.workspace }}/info.json)"

      # Make destination directory
      - name: Make dest directory
        run: "mkdir ./${{steps.extract_info.outputs.mod_name}}"
      
      # Copy items into dest folder
      - name: Copy files
        run: |
          ls -l
          cp -r !(.git|.github|${{steps.extract_info.outputs.mod_name}}) ./${{steps.extract_info.outputs.mod_name}}/
          ls -l ./${{steps.extract_info.outputs.mod_name}}

      # Upload the dest folder
      - name: Upload the mod
        uses: actions/upload-artifact@v3
        with:
          name: "${{steps.extract_info.outputs.mod_name}}_${{steps.extract_info.outputs.mod_version}}"
          path: "${{ github.workspace }}/${{steps.extract_info.outputs.mod_name}}"
          if-no-files-found: error
          retention-days: 1
